import LoadingCircle from '@/components/loading/loading-circle'
import SimpleDialog from '@/components/modal/SimpleDialog'
import { SidebarProvider } from '@/contexts/SidebarContext'
import Sidebar from '@/layouts/SidebarLayout/Sidebar/Sidebar'
import { Inter } from 'next/font/google'
import { Suspense } from 'react'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Dahsboard HardwateStore',
  description: 'Generated by create next app',
}

export default function Layout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <Suspense fallback={<LoadingCircle/>}>
      <SidebarProvider>
        <Sidebar>{children}</Sidebar>
        {/* <SimpleDialog>
              <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Itaque vitae vel 
                  consequatur nihil iste, dolore atque necessitatibus vero rem temporibus 
                  eum deleniti esse veritatis inventore quos eaque ipsum veniam amet.</p>
          </SimpleDialog> */}
      </SidebarProvider>
    </Suspense>
  )
}